import { lazy } from 'react';
import type { LazyExoticComponent, ComponentType, ElementType } from 'react';
import type { Permission, UserRole } from './types';
import {
  LayoutDashboard, ClipboardList, ReceiptText, Landmark, Ship, Package,
  Truck, BarChart3, Settings, FilePlus2, LifeBuoy, Activity, Users, Layers,
  Building2, Anchor, MapPin, ShieldAlert,
} from 'lucide-react';

export type ScreenGroup = 'operations' | 'supplier' | 'administration';

export interface ScreenEntry {
  id: string;
  path: string;
  label: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  icon: ElementType<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: LazyExoticComponent<ComponentType<any>>;
  allowedRoles: UserRole[];
  permissions: Permission[];
  group?: ScreenGroup;
  hideInSidebar?: true;
  badge?: (ctx: { openTicketsCount: number }) => number | undefined;
}

const ALL_ROLES: UserRole[] = ['user', 'admin', 'supadmin'];

export const SCREEN_REGISTRY: ScreenEntry[] = [
  // ── Hidden shell routes ──────────────────────────────────────────────────
  {
    id: 'access-pending',
    path: '/access-pending',
    label: 'Access Pending',
    icon: LifeBuoy,
    component: lazy(() => import('./pages/AccessPending').then(m => ({ default: m.AccessPending }))),
    allowedRoles: ALL_ROLES,
    permissions: [],
    hideInSidebar: true,
  },
  {
    id: 'profile',
    path: '/profile',
    label: 'My Profile',
    icon: LifeBuoy,
    component: lazy(() => import('./pages/Profile').then(m => ({ default: m.Profile }))),
    allowedRoles: ALL_ROLES,
    permissions: [],
    hideInSidebar: true,
  },

  // ── Operations ───────────────────────────────────────────────────────────
  {
    id: 'dashboard',
    path: '/customer/dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    component: lazy(() => import('./pages/customer/Dashboard').then(m => ({ default: m.CustomerDashboard }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:dashboard'],
    group: 'operations',
  },
  {
    id: 'operational-list',
    path: '/customer/operational-list',
    label: 'Operational List',
    icon: ClipboardList,
    component: lazy(() => import('./pages/customer/OperationalList').then(m => ({ default: m.OperationalList }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:operational-list'],
    group: 'operations',
  },
  {
    id: 'invoices',
    path: '/customer/invoices',
    label: 'Invoice List',
    icon: ReceiptText,
    component: lazy(() => import('./pages/customer/InvoiceList').then(m => ({ default: m.InvoiceList }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:invoices'],
    group: 'operations',
  },
  {
    id: 'port-fees',
    path: '/customer/port-fees',
    label: 'Port Fee List',
    icon: Landmark,
    component: lazy(() => import('./pages/customer/PortFeeList').then(m => ({ default: m.PortFeeList }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:port-fees'],
    group: 'operations',
  },
  {
    id: 'fleet',
    path: '/customer/fleet',
    label: 'Fleet Management',
    icon: Ship,
    component: lazy(() => import('./pages/customer/Fleet').then(m => ({ default: m.Fleet }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:fleet'],
    group: 'operations',
  },
  {
    id: 'orders',
    path: '/customer/orders',
    label: 'Orders',
    icon: Package,
    component: lazy(() => import('./pages/customer/Orders').then(m => ({ default: m.CustomerOrders }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:orders'],
    group: 'operations',
  },
  {
    id: 'historical-orders',
    path: '/customer/historical-orders',
    label: 'Historical Orders',
    icon: ClipboardList,
    component: lazy(() => import('./pages/customer/HistoricalOrders').then(m => ({ default: m.HistoricalOrders }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:orders'],
    group: 'operations',
  },
  {
    id: 'shipments',
    path: '/customer/shipments',
    label: 'Shipments',
    icon: Truck,
    component: lazy(() => import('./pages/customer/Shipments').then(m => ({ default: m.Shipments }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:shipments'],
    group: 'operations',
  },
  {
    id: 'finance',
    path: '/customer/finance',
    label: 'Finance',
    icon: Landmark,
    component: lazy(() => import('./pages/customer/Finance').then(m => ({ default: m.Finance }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:finance'],
    group: 'operations',
  },
  {
    id: 'sustainability',
    path: '/customer/sustainability',
    label: 'Sustainability',
    icon: BarChart3,
    component: lazy(() => import('./pages/customer/Sustainability').then(m => ({ default: m.Sustainability }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:sustainability'],
    group: 'operations',
  },
  {
    id: 'business',
    path: '/customer/business',
    label: 'Business',
    icon: Settings,
    component: lazy(() => import('./pages/customer/Business').then(m => ({ default: m.Business }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:business'],
    group: 'operations',
  },
  {
    id: 'analysis-report',
    path: '/customer/reports/analysis',
    label: 'Analysis Report',
    icon: BarChart3,
    component: lazy(() => import('./pages/customer/ContractedAnalysisReport').then(m => ({ default: m.ContractedAnalysisReport }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:reports'],
    group: 'operations',
  },
  {
    id: 'guest-rfq',
    path: '/guest/rfq',
    label: 'Guest RFQ',
    icon: FilePlus2,
    component: lazy(() => import('./pages/guest/RFQ').then(m => ({ default: m.GuestRFQPage }))),
    allowedRoles: ['user'],
    permissions: ['submit:rfq'],
    group: 'operations',
  },
  {
    id: 'support-tickets',
    path: '/support/tickets',
    label: 'Support Tickets',
    icon: LifeBuoy,
    component: lazy(() => import('./pages/shared/SupportTickets').then(m => ({ default: m.SupportTickets }))),
    allowedRoles: ['user', 'admin'],
    permissions: ['create:support-ticket'],
    group: 'operations',
  },

  // ── Supplier ─────────────────────────────────────────────────────────────
  {
    id: 'supplier-dashboard',
    path: '/supplier/dashboard',
    label: 'Supplier Dashboard',
    icon: LayoutDashboard,
    component: lazy(() => import('./pages/supplier/Dashboard').then(m => ({ default: m.SupplierDashboard }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:supplier'],
    group: 'supplier',
  },
  {
    id: 'supplier-orders',
    path: '/supplier/orders',
    label: 'Supplier Orders',
    icon: Package,
    component: lazy(() => Promise.resolve({ default: () => <div className="p-6">Supplier Orders View</div> })),
    allowedRoles: ALL_ROLES,
    permissions: ['view:supplier'],
    group: 'supplier',
  },
  {
    id: 'supplier-logistics',
    path: '/supplier/logistics',
    label: 'Supplier Logistics',
    icon: Truck,
    component: lazy(() => import('./pages/supplier/Logistics').then(m => ({ default: m.SupplierLogistics }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:supplier'],
    group: 'supplier',
  },
  {
    id: 'supplier-performance',
    path: '/supplier/performance',
    label: 'Supplier Performance',
    icon: BarChart3,
    component: lazy(() => Promise.resolve({ default: () => <div className="p-6">Performance Scorecards</div> })),
    allowedRoles: ALL_ROLES,
    permissions: ['view:supplier'],
    group: 'supplier',
  },

  // ── Administration ───────────────────────────────────────────────────────
  {
    id: 'system-health',
    path: '/admin/system-health',
    label: 'System Health',
    icon: Activity,
    component: lazy(() => import('./pages/admin/SystemHealth').then(m => ({ default: m.SystemHealth }))),
    allowedRoles: ['admin', 'supadmin'],
    permissions: ['system:settings'],
    group: 'administration',
  },
  {
    id: 'users',
    path: '/admin/users',
    label: 'User Management',
    icon: Users,
    component: lazy(() => import('./pages/admin/UserManagement').then(m => ({ default: m.UserManagement }))),
    allowedRoles: ['admin', 'supadmin'],
    permissions: ['manage:users'],
    group: 'administration',
  },
  {
    id: 'user-templates',
    path: '/company/user-templates',
    label: 'Role Templates',
    icon: Layers,
    component: lazy(() => import('./pages/customer/UserTemplateManagement').then(m => ({ default: m.UserTemplateManagement }))),
    allowedRoles: ['admin'],
    permissions: ['manage:templates'],
    group: 'administration',
  },
  {
    id: 'entities',
    path: '/admin/entities',
    label: 'Entity Management',
    icon: Building2,
    component: lazy(() => import('./pages/admin/EntityManagement').then(m => ({ default: m.EntityManagement }))),
    allowedRoles: ['supadmin'],
    permissions: ['manage:companies'],
    group: 'administration',
  },
  {
    id: 'vessels',
    path: '/admin/vessels',
    label: 'Vessel Management',
    icon: Anchor,
    component: lazy(() => import('./pages/admin/VesselManagement').then(m => ({ default: m.VesselManagement }))),
    allowedRoles: ['supadmin'],
    permissions: ['manage:vessels'],
    group: 'administration',
  },
  {
    id: 'maritime-map',
    path: '/customer/maritime-map',
    label: 'Maritime Map',
    icon: MapPin,
    component: lazy(() => import('./pages/customer/MaritimeMap').then(m => ({ default: m.MaritimeMap }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:maritime-map'],
    group: 'operations',
  },
  {
    id: 'maritime-map-detail',
    path: '/customer/maritime-map/operations/:vesselId',
    label: 'Maritime Operation Detail',
    icon: MapPin,
    component: lazy(() => import('./pages/customer/MaritimeOperationDetail').then(m => ({ default: m.MaritimeOperationDetail }))),
    allowedRoles: ALL_ROLES,
    permissions: ['view:maritime-map'],
    group: 'operations',
    hideInSidebar: true,
  },
  {
    id: 'reports-management',
    path: '/admin/reports',
    label: 'Report Management',
    icon: BarChart3,
    component: lazy(() => import('./pages/admin/ReportManagement').then(m => ({ default: m.ReportManagement }))),
    allowedRoles: ['supadmin'],
    permissions: [],
    group: 'administration',
  },
  {
    id: 'templates',
    path: '/admin/templates',
    label: 'Templates',
    icon: Layers,
    component: lazy(() => import('./pages/admin/TemplateManagement').then(m => ({ default: m.TemplateManagement }))),
    allowedRoles: ['supadmin'],
    permissions: ['manage:templates'],
    group: 'administration',
  },
  {
    id: 'support-tickets-admin',
    path: '/admin/support-tickets',
    label: 'Support Tickets',
    icon: LifeBuoy,
    component: lazy(() => import('./pages/admin/SupportTicketManagement').then(m => ({ default: m.SupportTicketManagement }))),
    allowedRoles: ['supadmin'],
    permissions: [],
    group: 'administration',
    badge: (ctx) => ctx.openTicketsCount > 0 ? ctx.openTicketsCount : undefined,
  },
  {
    id: 'security',
    path: '/admin/security',
    label: 'Security Logs',
    icon: ShieldAlert,
    component: lazy(() => import('./pages/admin/Security').then(m => ({ default: m.Security }))),
    allowedRoles: ['admin', 'supadmin'],
    permissions: ['system:settings'],
    group: 'administration',
  },
  {
    id: 'feature-flags',
    path: '/admin/feature-flags',
    label: 'Feature Flags',
    icon: Settings,
    component: lazy(() => Promise.resolve({ default: () => <div className="p-6">Feature Flags Management</div> })),
    allowedRoles: ['admin', 'supadmin'],
    permissions: ['system:settings'],
    group: 'administration',
  },
];
