
import React, { useEffect, useState } from 'react';
import { api } from '../../services/api';
import { User, Permission, UserRole, Company } from '../../types';
import { Card } from '../../components/ui/Card';
import { useUIStore } from '../../store/uiStore';
import { Trash2, Edit2, Plus, X, Save, Check, Search } from 'lucide-react';

const ALL_PERMISSIONS: Permission[] = [
    'manage:users', 'manage:companies', 'view:finance', 'edit:orders', 'view:analytics', 'system:settings'
];

export const UserManagement: React.FC = () => {
    const [users, setUsers] = useState<User[]>([]);
    const [companies, setCompanies] = useState<Company[]>([]);
    const { addToast, openDrawer, closeDrawer } = useUIStore();
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        const [u, c] = await Promise.all([api.admin.getUsers(), api.admin.getCompanies()]);
        setUsers(u);
        setCompanies(c);
    };

    const handleDelete = async (id: string) => {
        if (confirm('Are you sure you want to delete this user?')) {
            await api.admin.deleteUser(id);
            setUsers(users.filter(u => u.id !== id));
            addToast({ title: 'User Deleted', message: 'User removed successfully.', type: 'info' });
        }
    };

    const handleSaveUser = async (userData: Partial<User>, isNew: boolean) => {
        try {
            if (isNew) {
                // @ts-ignore - id generated by api
                const newUser = await api.admin.createUser(userData);
                setUsers([...users, newUser]);
                addToast({ title: 'User Created', message: 'New user added.', type: 'success' });
            } else {
                if (!userData.id) return;
                const updated = await api.admin.updateUser(userData.id, userData);
                setUsers(users.map(u => u.id === updated.id ? updated : u));
                addToast({ title: 'User Updated', message: 'User details saved.', type: 'success' });
            }
            closeDrawer();
        } catch (e) {
            addToast({ title: 'Error', message: 'Operation failed.', type: 'error' });
        }
    };

    const openUserDrawer = (user?: User) => {
        openDrawer(<UserForm user={user} companies={companies} onSave={(data) => handleSaveUser(data, !user)} onCancel={closeDrawer} />);
    };

    const filteredUsers = users.filter(u => 
        u.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
        u.email.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold text-slate-900 dark:text-white">User Management</h1>
                <button 
                    onClick={() => openUserDrawer()}
                    className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium shadow-lg shadow-blue-500/20 transition-all"
                >
                    <Plus size={16} strokeWidth={1.5} /> <span>Add User</span>
                </button>
            </div>

            <Card className="overflow-hidden" noPadding>
                <div className="px-6 py-4 border-b border-gray-100 dark:border-slate-800 flex justify-between items-center bg-gray-50/50 dark:bg-slate-900">
                    <div className="relative w-64">
                        <input 
                            type="text" 
                            placeholder="Search users..." 
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="w-full pl-9 pr-4 py-2 bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50"
                        />
                        <Search className="absolute left-3 top-2.5 text-slate-400" size={14} />
                    </div>
                </div>
                <table className="w-full text-left border-collapse">
                    <thead className="bg-gray-50 dark:bg-slate-800/50 border-b border-gray-200 dark:border-slate-800">
                        <tr>
                            <th className="px-6 py-3 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">User</th>
                            <th className="px-6 py-3 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Role & Company</th>
                            <th className="px-6 py-3 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Permissions</th>
                            <th className="px-6 py-3 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Status</th>
                            <th className="px-6 py-3"></th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200 dark:divide-slate-800">
                        {filteredUsers.map(user => (
                            <tr key={user.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                                <td className="px-6 py-4">
                                    <div className="flex items-center">
                                        <div className="w-8 h-8 rounded-full bg-slate-200 dark:bg-slate-700 flex items-center justify-center text-xs font-bold mr-3">
                                            {user.name.charAt(0)}
                                        </div>
                                        <div>
                                            <p className="font-medium text-slate-900 dark:text-white text-sm">{user.name}</p>
                                            <p className="text-xs text-slate-500 dark:text-slate-400">{user.email}</p>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex flex-col">
                                        <span className="text-sm text-slate-900 dark:text-slate-200">{user.role}</span>
                                        <span className="text-xs text-slate-500">{user.companyId || 'No Company'}</span>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex flex-wrap gap-1">
                                        {user.permissions.slice(0, 3).map(p => (
                                            <span key={p} className="px-1.5 py-0.5 bg-gray-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 text-[10px] rounded border border-gray-200 dark:border-slate-700">{p}</span>
                                        ))}
                                        {user.permissions.length > 3 && <span className="text-[10px] text-slate-400">+{user.permissions.length - 3} more</span>}
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`px-2 py-1 rounded-full text-xs font-medium border ${
                                        user.status === 'Active' ? 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800' :
                                        'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-400 dark:border-red-800'
                                    }`}>
                                        {user.status}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-right space-x-2">
                                    <button onClick={() => openUserDrawer(user)} className="text-blue-500 hover:text-blue-600 dark:hover:text-blue-400"><Edit2 size={16} /></button>
                                    <button onClick={() => handleDelete(user.id)} className="text-red-500 hover:text-red-600 dark:hover:text-red-400"><Trash2 size={16} /></button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </Card>
        </div>
    );
};

const UserForm = ({ user, companies, onSave, onCancel }: { user?: User, companies: Company[], onSave: (data: Partial<User>) => void, onCancel: () => void }) => {
    const [formData, setFormData] = useState<Partial<User>>({
        id: user?.id,
        name: user?.name || '',
        email: user?.email || '',
        role: user?.role || 'Customer',
        companyId: user?.companyId || '',
        status: user?.status || 'Active',
        permissions: user?.permissions || []
    });

    const togglePermission = (perm: Permission) => {
        setFormData(prev => {
            const perms = prev.permissions || [];
            if (perms.includes(perm)) return { ...prev, permissions: perms.filter(p => p !== perm) };
            return { ...prev, permissions: [...perms, perm] };
        });
    };

    return (
        <div className="space-y-6">
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">{user ? 'Edit User' : 'Create User'}</h2>
            
            <div className="space-y-4">
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Full Name</label>
                    <input className="w-full p-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded text-sm text-slate-900 dark:text-white"
                           value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Email</label>
                    <input className="w-full p-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded text-sm text-slate-900 dark:text-white"
                           value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Role</label>
                        <select className="w-full p-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded text-sm text-slate-900 dark:text-white"
                                value={formData.role} onChange={e => setFormData({...formData, role: e.target.value as UserRole})}>
                            <option value="Customer">Customer</option>
                            <option value="Supplier">Supplier</option>
                            <option value="Admin">Admin</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Status</label>
                        <select className="w-full p-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded text-sm text-slate-900 dark:text-white"
                                value={formData.status} onChange={e => setFormData({...formData, status: e.target.value as any})}>
                            <option value="Active">Active</option>
                            <option value="Inactive">Inactive</option>
                            <option value="Suspended">Suspended</option>
                        </select>
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Company</label>
                    <select className="w-full p-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded text-sm text-slate-900 dark:text-white"
                            value={formData.companyId} onChange={e => setFormData({...formData, companyId: e.target.value})}>
                        <option value="">-- None (Admin) --</option>
                        {companies.map(c => <option key={c.id} value={c.id}>{c.name} ({c.type})</option>)}
                    </select>
                </div>

                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Permissions</label>
                    <div className="grid grid-cols-2 gap-2">
                        {ALL_PERMISSIONS.map(p => (
                            <div key={p} 
                                 onClick={() => togglePermission(p)}
                                 className={`cursor-pointer px-3 py-2 rounded text-xs border flex items-center justify-between transition-colors ${formData.permissions?.includes(p) ? 'bg-blue-50 border-blue-200 text-blue-700 dark:bg-blue-900/20 dark:border-blue-800 dark:text-blue-300' : 'bg-gray-50 border-gray-200 text-slate-600 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-400'}`}>
                                <span>{p}</span>
                                {formData.permissions?.includes(p) && <Check size={12} />}
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <div className="flex justify-end space-x-3 pt-4 border-t border-gray-100 dark:border-slate-800">
                <button onClick={onCancel} className="px-4 py-2 text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">Cancel</button>
                <button onClick={() => onSave(formData)} className="bg-blue-600 text-white px-4 py-2 rounded text-sm hover:bg-blue-700 shadow-md">Save User</button>
            </div>
        </div>
    );
};
